all: project4_algo1_semaphore project4_algo2_semaphore project4_algo3_semaphore 

project4_algo1_semaphore:
	gcc -g -o project4_algo1_semaphore project4_algo1_semaphore.c -pthread

project4_algo2_semaphore:
	gcc -g -o project4_algo2_semaphore project4_algo2_semaphore.c -pthread

project4_algo3_semaphore:
	gcc -g -o project4_algo3_semaphore project4_algo3_semaphore.c -pthread

clean:
	rm -rf *.o project4_algo1_semaphore project4_algo2_semaphore project4_algo3_semaphore
