all: 
	gcc -Wall -o runCommand runCommand.c
	gcc -Wall -o shell shell.c
	gcc -Wall -o shell2 shell2.c

runCommand:
	gcc -Wall -o runCommand runCommand.c

shell:
	gcc -Wall -o shell shell.c

shell2:
	gcc -Wall -o shell2 shell2.c

clean:
	rm *.o
